<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Maaf, kata sandi Anda salah. Harap periksa kembali kata sandi Anda</name>
   <tag></tag>
   <elementGuidId>04aca5af-5410-4f8c-801c-1c204a4cd72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='slfErrorAlert']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slfErrorAlert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2a26477d-184b-40c4-b6b3-1dcb74946d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>397ad8dc-8004-43af-adf4-6938a66c883d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slfErrorAlert</value>
      <webElementGuid>a18a79cf-2bda-4a44-8f1c-0590978104d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>873f59eb-d8fe-4b4d-80a9-17b40aaa57e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maaf, kata sandi Anda salah. Harap periksa kembali kata sandi Anda.</value>
      <webElementGuid>3cb4bee3-7880-4bfc-9157-0d2f645ac46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slfErrorAlert&quot;)</value>
      <webElementGuid>94bb9113-e873-463c-bed8-7932298df980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='slfErrorAlert']</value>
      <webElementGuid>3735a7ea-426f-49a2-80c6-20f7c8e30b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/p</value>
      <webElementGuid>191b209a-aefe-4bdd-bd3e-4af13590afdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk dengan Facebook'])[1]/following::p[1]</value>
      <webElementGuid>732dc5dd-8195-4213-9f3c-84e7bef7bc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/following::p[1]</value>
      <webElementGuid>478be251-7759-4274-b784-5f3146076e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/preceding::p[1]</value>
      <webElementGuid>261d740d-e31b-4609-b5b1-b2a8f4e2e069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat akun'])[1]/preceding::p[1]</value>
      <webElementGuid>d59f0bca-fb7e-4055-a62c-d74dffeb4d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maaf, kata sandi Anda salah. Harap periksa kembali kata sandi Anda.']/parent::*</value>
      <webElementGuid>0b204fb5-bdbc-44e7-a0ad-24f024fb399c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>91430fe2-dc96-452c-8f08-ead032e34584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'slfErrorAlert' and (text() = 'Maaf, kata sandi Anda salah. Harap periksa kembali kata sandi Anda.' or . = 'Maaf, kata sandi Anda salah. Harap periksa kembali kata sandi Anda.')]</value>
      <webElementGuid>0db733aa-6836-4762-b74b-c5ca263a0808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
